import Link from 'next/link';
import { AdminBadge, AdminEmptyState, AdminFilterBar, AdminPageFrame, AdminPageHeader } from '@/components/admin/AdminLayout';
import { listStoreIntegrationsWithSource } from '@/modules/integrations/core/store-integration.service';
import { resolveCurrentStoreFromHeaders } from '@/modules/stores/store-resolution';

const routes: Record<string,string> = { bling: '/admin/integracoes/bling', whatsapp: '/admin/integracoes/whatsapp', evolution_whatsapp: '/admin/integracoes/whatsapp', marketing: '/admin/integracoes/marketing', mercado_pago: '/admin/integracoes/mercado-pago' };
const statusLabel: Record<string,string> = { connected:'Conectado', syncing:'Sincronizando', error:'Requer atenção', planned:'Planejado', pending_credentials:'Configuração pendente', disconnected:'Desconectado', disabled:'Desativado' };

export default async function IntegrationsPage({ searchParams }: { searchParams: Promise<{q?:string;status?:string}> }) {
  const params=await searchParams; const store=await resolveCurrentStoreFromHeaders(); const result=await listStoreIntegrationsWithSource(store.id); const q=params.q?.trim().toLowerCase()??''; const status=params.status??'all';
  const items=result.data.filter((item)=>(!q||`${item.provider.name} ${item.provider.description??''}`.toLowerCase().includes(q))&&(status==='all'||(item.integration?.status??'planned')===status));
  return <AdminPageFrame><AdminPageHeader eyebrow="Conectores" title="Integrações" description="Conecte e gerencie os serviços da sua loja a partir de um único catálogo."/><div className="space-y-4 pt-4"><AdminFilterBar action="/admin/integracoes" query={params.q} status={status} placeholder="Buscar integração…" statuses={[{value:'all',label:'Todos os status'},{value:'connected',label:'Conectados'},{value:'planned',label:'Planejados'},{value:'error',label:'Com atenção'}]}/>{items.length?<div className="grid gap-3 md:grid-cols-2 2xl:grid-cols-3">{items.map((item)=>{const integrationStatus=item.integration?.status??'planned';const href=routes[item.provider.key];return <article key={item.provider.id} className="flex min-h-44 flex-col rounded-xl border border-white/7 bg-[linear-gradient(150deg,#0A1730,#071225)] p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="text-sm font-semibold text-white">{item.provider.name}</h2><p className="mt-2 line-clamp-2 text-xs leading-5 text-slate-400">{item.provider.description??'Serviço disponível para a operação da loja.'}</p></div><AdminBadge tone={integrationStatus==='connected'?'success':integrationStatus==='error'?'danger':integrationStatus==='planned'?'warning':'neutral'}>{statusLabel[integrationStatus]??'Disponível'}</AdminBadge></div><div className="mt-auto pt-5">{href?<Link href={href} className="text-xs font-semibold text-blue-300 hover:text-blue-200">{integrationStatus==='connected'?'Gerenciar':'Ver detalhes'} →</Link>:<span className="text-xs text-slate-500">Disponibilidade futura</span>}</div></article>})}</div>:<AdminEmptyState title="Nenhuma integração encontrada" description="Altere a busca ou o filtro para ver outros conectores."/>}</div></AdminPageFrame>;
}
